[controller]
host = "http://localhost:8000/"
SecrectKey = "0xffffffff"
AccessKey = "ox00000000"
[self]
judgeCapability = 6
name = "TestJudger"
version = "0.0.1"
[hc]
path = "/usr/local/bin/hc"
[nsjail]
path = "/usr/bin/nsjail"
configFile = "./jailConfig.cfg"
[language]
c = "/usr/bin/gcc"
cpp = "/usr/bin/g++"
python = "/usr/bin/python3"
java = "/usr/bin/java"
javac = "/usr/bin/javac"
[judger]
timeRatioTolerance = 5
[[judger.testcases]]
cwd = "./selfTest/5s"
src = "5s.cpp"
language = "cpp"
timeExpected = 5
