[controller]
host="http://localhost:8888"
SecrectKey="0xffffffff"
AccessKey="ox00000000"
[self]
judgeCapability=6
name="TestJudger"
version="0.0.1"
[language.c]
compiler="/usr/bin/gcc"
[language.c.c99]
compilearg=[":input","-O2","-std=c99","-o",":output"]
[language.c.c11]
compilearg=[":input","-O2","-std=c11","-o",":output"]
[language.cpp]
compiler="/usr/bin/g++"
[language.cpp.cpp20]
compilearg=[":input","-O2","-std=c++20","-o",":output"]
